// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RealEstateAPI.Data;

#nullable disable

namespace RealEstateAPI.Migrations
{
    [DbContext(typeof(RealEstateDbContext))]
    [Migration("20251115231903_SeedData")]
    partial class SeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("RealEstateAPI.Models.Property", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Bathrooms")
                        .HasColumnType("int");

                    b.Property<int>("Bedrooms")
                        .HasColumnType("int");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("ListedDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("PropertyType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("RealtorId")
                        .HasColumnType("int");

                    b.Property<int>("SquareFeet")
                        .HasColumnType("int");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ZipCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("Id");

                    b.HasIndex("RealtorId");

                    b.ToTable("Properties");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "1234 Sunset Blvd",
                            Bathrooms = 3,
                            Bedrooms = 4,
                            City = "Los Angeles",
                            Description = "Beautiful modern home with stunning views",
                            ListedDate = new DateTime(2024, 10, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Price = 850000m,
                            PropertyType = "House",
                            RealtorId = 1,
                            SquareFeet = 2500,
                            State = "CA",
                            Status = "Available",
                            ZipCode = "90028"
                        },
                        new
                        {
                            Id = 2,
                            Address = "567 Park Avenue",
                            Bathrooms = 2,
                            Bedrooms = 3,
                            City = "New York",
                            Description = "Luxury condo in prime location",
                            ListedDate = new DateTime(2024, 10, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Price = 1200000m,
                            PropertyType = "Condo",
                            RealtorId = 2,
                            SquareFeet = 1800,
                            State = "NY",
                            Status = "Available",
                            ZipCode = "10022"
                        },
                        new
                        {
                            Id = 3,
                            Address = "890 Lake Shore Drive",
                            Bathrooms = 2,
                            Bedrooms = 2,
                            City = "Chicago",
                            Description = "Lakefront apartment with amazing amenities",
                            ListedDate = new DateTime(2024, 9, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Price = 675000m,
                            PropertyType = "Apartment",
                            RealtorId = 3,
                            SquareFeet = 1500,
                            State = "IL",
                            Status = "Pending",
                            ZipCode = "60611"
                        },
                        new
                        {
                            Id = 4,
                            Address = "2345 Ocean View Road",
                            Bathrooms = 4,
                            Bedrooms = 5,
                            City = "Miami",
                            Description = "Beachfront property with private access",
                            ListedDate = new DateTime(2024, 10, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Price = 950000m,
                            PropertyType = "House",
                            RealtorId = 4,
                            SquareFeet = 3200,
                            State = "FL",
                            Status = "Available",
                            ZipCode = "33139"
                        },
                        new
                        {
                            Id = 5,
                            Address = "678 Mountain Trail",
                            Bathrooms = 3,
                            Bedrooms = 4,
                            City = "Denver",
                            Description = "Mountain retreat with panoramic views",
                            ListedDate = new DateTime(2024, 10, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Price = 725000m,
                            PropertyType = "House",
                            RealtorId = 5,
                            SquareFeet = 2800,
                            State = "CO",
                            Status = "Available",
                            ZipCode = "80202"
                        },
                        new
                        {
                            Id = 6,
                            Address = "901 Downtown Plaza",
                            Bathrooms = 2,
                            Bedrooms = 2,
                            City = "Seattle",
                            Description = "Modern downtown condo near tech hub",
                            ListedDate = new DateTime(2024, 8, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Price = 580000m,
                            PropertyType = "Condo",
                            RealtorId = 6,
                            SquareFeet = 1400,
                            State = "WA",
                            Status = "Sold",
                            ZipCode = "98101"
                        },
                        new
                        {
                            Id = 7,
                            Address = "3456 Suburban Lane",
                            Bathrooms = 2,
                            Bedrooms = 3,
                            City = "Austin",
                            Description = "Family-friendly home in great school district",
                            ListedDate = new DateTime(2024, 10, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Price = 495000m,
                            PropertyType = "House",
                            RealtorId = 7,
                            SquareFeet = 2000,
                            State = "TX",
                            Status = "Available",
                            ZipCode = "78701"
                        },
                        new
                        {
                            Id = 8,
                            Address = "789 Historic District",
                            Bathrooms = 3,
                            Bedrooms = 3,
                            City = "Boston",
                            Description = "Charming historic townhouse fully renovated",
                            ListedDate = new DateTime(2024, 10, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Price = 890000m,
                            PropertyType = "Townhouse",
                            RealtorId = 8,
                            SquareFeet = 2200,
                            State = "MA",
                            Status = "Available",
                            ZipCode = "02101"
                        },
                        new
                        {
                            Id = 9,
                            Address = "1122 Desert Vista",
                            Bathrooms = 2,
                            Bedrooms = 3,
                            City = "Phoenix",
                            Description = "Desert oasis with pool and landscaping",
                            ListedDate = new DateTime(2024, 10, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Price = 425000m,
                            PropertyType = "House",
                            RealtorId = 9,
                            SquareFeet = 1900,
                            State = "AZ",
                            Status = "Available",
                            ZipCode = "85001"
                        },
                        new
                        {
                            Id = 10,
                            Address = "4567 Music Row",
                            Bathrooms = 3,
                            Bedrooms = 4,
                            City = "Nashville",
                            Description = "Contemporary home near entertainment district",
                            ListedDate = new DateTime(2024, 9, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Price = 615000m,
                            PropertyType = "House",
                            RealtorId = 10,
                            SquareFeet = 2400,
                            State = "TN",
                            Status = "Pending",
                            ZipCode = "37201"
                        });
                });

            modelBuilder.Entity("RealEstateAPI.Models.Realtor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Agency")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("LicenseNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Specialization")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("YearsOfExperience")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("LicenseNumber")
                        .IsUnique();

                    b.ToTable("Realtors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Agency = "Prime Realty Group",
                            Email = "sarah.johnson@realty.com",
                            FirstName = "Sarah",
                            IsActive = true,
                            LastName = "Johnson",
                            LicenseNumber = "RE-2024-001",
                            PhoneNumber = "555-0101",
                            Specialization = "Residential",
                            YearsOfExperience = 8
                        },
                        new
                        {
                            Id = 2,
                            Agency = "Luxury Estates Inc",
                            Email = "michael.chen@realty.com",
                            FirstName = "Michael",
                            IsActive = true,
                            LastName = "Chen",
                            LicenseNumber = "RE-2024-002",
                            PhoneNumber = "555-0102",
                            Specialization = "Luxury Homes",
                            YearsOfExperience = 12
                        },
                        new
                        {
                            Id = 3,
                            Agency = "Urban Living Realty",
                            Email = "emily.rodriguez@realty.com",
                            FirstName = "Emily",
                            IsActive = true,
                            LastName = "Rodriguez",
                            LicenseNumber = "RE-2024-003",
                            PhoneNumber = "555-0103",
                            Specialization = "Condos",
                            YearsOfExperience = 5
                        },
                        new
                        {
                            Id = 4,
                            Agency = "Coastal Properties",
                            Email = "david.thompson@realty.com",
                            FirstName = "David",
                            IsActive = true,
                            LastName = "Thompson",
                            LicenseNumber = "RE-2024-004",
                            PhoneNumber = "555-0104",
                            Specialization = "Waterfront",
                            YearsOfExperience = 15
                        },
                        new
                        {
                            Id = 5,
                            Agency = "Metro Realty Partners",
                            Email = "jessica.martinez@realty.com",
                            FirstName = "Jessica",
                            IsActive = true,
                            LastName = "Martinez",
                            LicenseNumber = "RE-2024-005",
                            PhoneNumber = "555-0105",
                            Specialization = "Commercial",
                            YearsOfExperience = 6
                        },
                        new
                        {
                            Id = 6,
                            Agency = "Family Home Realty",
                            Email = "robert.anderson@realty.com",
                            FirstName = "Robert",
                            IsActive = true,
                            LastName = "Anderson",
                            LicenseNumber = "RE-2024-006",
                            PhoneNumber = "555-0106",
                            Specialization = "Family Homes",
                            YearsOfExperience = 10
                        },
                        new
                        {
                            Id = 7,
                            Agency = "Downtown Realty",
                            Email = "amanda.lee@realty.com",
                            FirstName = "Amanda",
                            IsActive = true,
                            LastName = "Lee",
                            LicenseNumber = "RE-2024-007",
                            PhoneNumber = "555-0107",
                            Specialization = "Urban",
                            YearsOfExperience = 4
                        },
                        new
                        {
                            Id = 8,
                            Agency = "Suburban Living Realty",
                            Email = "chris.wilson@realty.com",
                            FirstName = "Christopher",
                            IsActive = true,
                            LastName = "Wilson",
                            LicenseNumber = "RE-2024-008",
                            PhoneNumber = "555-0108",
                            Specialization = "Suburban",
                            YearsOfExperience = 9
                        },
                        new
                        {
                            Id = 9,
                            Agency = "Investment Properties LLC",
                            Email = "nicole.brown@realty.com",
                            FirstName = "Nicole",
                            IsActive = true,
                            LastName = "Brown",
                            LicenseNumber = "RE-2024-009",
                            PhoneNumber = "555-0109",
                            Specialization = "Investment",
                            YearsOfExperience = 7
                        },
                        new
                        {
                            Id = 10,
                            Agency = "Green Valley Realty",
                            Email = "james.taylor@realty.com",
                            FirstName = "James",
                            IsActive = true,
                            LastName = "Taylor",
                            LicenseNumber = "RE-2024-010",
                            PhoneNumber = "555-0110",
                            Specialization = "Rural",
                            YearsOfExperience = 11
                        });
                });

            modelBuilder.Entity("RealEstateAPI.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "123 Main St, Anytown, CA 90210",
                            CreatedDate = new DateTime(2024, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "john.smith@email.com",
                            FirstName = "John",
                            IsActive = true,
                            LastName = "Smith",
                            PhoneNumber = "555-1001"
                        },
                        new
                        {
                            Id = 2,
                            Address = "456 Oak Ave, Springfield, IL 62701",
                            CreatedDate = new DateTime(2024, 2, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "emma.davis@email.com",
                            FirstName = "Emma",
                            IsActive = true,
                            LastName = "Davis",
                            PhoneNumber = "555-1002"
                        },
                        new
                        {
                            Id = 3,
                            Address = "789 Pine Rd, Portland, OR 97201",
                            CreatedDate = new DateTime(2024, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "william.garcia@email.com",
                            FirstName = "William",
                            IsActive = true,
                            LastName = "Garcia",
                            PhoneNumber = "555-1003"
                        },
                        new
                        {
                            Id = 4,
                            Address = "321 Elm St, Austin, TX 78701",
                            CreatedDate = new DateTime(2024, 4, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "olivia.miller@email.com",
                            FirstName = "Olivia",
                            IsActive = true,
                            LastName = "Miller",
                            PhoneNumber = "555-1004"
                        },
                        new
                        {
                            Id = 5,
                            Address = "654 Maple Dr, Seattle, WA 98101",
                            CreatedDate = new DateTime(2024, 5, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "daniel.wilson@email.com",
                            FirstName = "Daniel",
                            IsActive = true,
                            LastName = "Wilson",
                            PhoneNumber = "555-1005"
                        },
                        new
                        {
                            Id = 6,
                            Address = "987 Cedar Ln, Denver, CO 80201",
                            CreatedDate = new DateTime(2024, 6, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "sophia.moore@email.com",
                            FirstName = "Sophia",
                            IsActive = true,
                            LastName = "Moore",
                            PhoneNumber = "555-1006"
                        },
                        new
                        {
                            Id = 7,
                            Address = "147 Birch Ct, Miami, FL 33101",
                            CreatedDate = new DateTime(2024, 7, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "matthew.taylor@email.com",
                            FirstName = "Matthew",
                            IsActive = true,
                            LastName = "Taylor",
                            PhoneNumber = "555-1007"
                        },
                        new
                        {
                            Id = 8,
                            Address = "258 Spruce Way, Boston, MA 02101",
                            CreatedDate = new DateTime(2024, 8, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "isabella.anderson@email.com",
                            FirstName = "Isabella",
                            IsActive = true,
                            LastName = "Anderson",
                            PhoneNumber = "555-1008"
                        },
                        new
                        {
                            Id = 9,
                            Address = "369 Willow Blvd, Phoenix, AZ 85001",
                            CreatedDate = new DateTime(2024, 9, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "ethan.thomas@email.com",
                            FirstName = "Ethan",
                            IsActive = true,
                            LastName = "Thomas",
                            PhoneNumber = "555-1009"
                        },
                        new
                        {
                            Id = 10,
                            Address = "741 Ash Pl, Nashville, TN 37201",
                            CreatedDate = new DateTime(2024, 10, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "mia.jackson@email.com",
                            FirstName = "Mia",
                            IsActive = true,
                            LastName = "Jackson",
                            PhoneNumber = "555-1010"
                        });
                });

            modelBuilder.Entity("RealEstateAPI.Models.Property", b =>
                {
                    b.HasOne("RealEstateAPI.Models.Realtor", "Realtor")
                        .WithMany("Properties")
                        .HasForeignKey("RealtorId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Realtor");
                });

            modelBuilder.Entity("RealEstateAPI.Models.Realtor", b =>
                {
                    b.Navigation("Properties");
                });
#pragma warning restore 612, 618
        }
    }
}
